//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpertRecommendationSystem {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ExpSysResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExpSysResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ExpertRecommendationSystem.ExpSysResources", typeof(ExpSysResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suggested Repair: Add gas..
        /// </summary>
        internal static string AddGasRepair {
            get {
                return ResourceManager.GetString("AddGasRepair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suggested Repair: Adjust timing..
        /// </summary>
        internal static string AdjustTimingRepair {
            get {
                return ResourceManager.GetString("AdjustTimingRepair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is the battery charged?.
        /// </summary>
        internal static string BatteryQuestion {
            get {
                return ResourceManager.GetString("BatteryQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suggested Repair: Clean the points..
        /// </summary>
        internal static string CleanPointsRepair {
            get {
                return ResourceManager.GetString("CleanPointsRepair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is the conductivity test for the ignition coil positive?.
        /// </summary>
        internal static string CoilQuestion {
            get {
                return ResourceManager.GetString("CoilQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suggested Repair: Replace the ignition coil..
        /// </summary>
        internal static string CoilRepair {
            get {
                return ResourceManager.GetString("CoilRepair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suggested Repair: Clean the fuel line..
        /// </summary>
        internal static string FuelLineRepair {
            get {
                return ResourceManager.GetString("FuelLineRepair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Does the tank have any gas in it?.
        /// </summary>
        internal static string GasQuestion {
            get {
                return ResourceManager.GetString("GasQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Does the engine knock?.
        /// </summary>
        internal static string KnockQuestion {
            get {
                return ResourceManager.GetString("KnockQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suggested Repair: Replace the distributor lead wire..
        /// </summary>
        internal static string LeadWireRepair {
            get {
                return ResourceManager.GetString("LeadWireRepair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suggested Repair: Take your car to a mechanic..
        /// </summary>
        internal static string MechanicRepair {
            get {
                return ResourceManager.GetString("MechanicRepair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Does the engine misfire?.
        /// </summary>
        internal static string MisfireQuestion {
            get {
                return ResourceManager.GetString("MisfireQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suggested Repair: None..
        /// </summary>
        internal static string NoRepair {
            get {
                return ResourceManager.GetString("NoRepair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is the output of the engine low?.
        /// </summary>
        internal static string OutputQuestion {
            get {
                return ResourceManager.GetString("OutputQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suggested Repair: Adjust point gap..
        /// </summary>
        internal static string PointGapRepair {
            get {
                return ResourceManager.GetString("PointGapRepair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is the surface state of the points?.
        /// </summary>
        internal static string PointsQuestion {
            get {
                return ResourceManager.GetString("PointsQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suggested Repair: Charge the battery..
        /// </summary>
        internal static string ReplaceBatteryRepair {
            get {
                return ResourceManager.GetString("ReplaceBatteryRepair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suggested Repair: Replace the points..
        /// </summary>
        internal static string ReplacePointsRepair {
            get {
                return ResourceManager.GetString("ReplacePointsRepair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Does the engine rotate?.
        /// </summary>
        internal static string RotateQuestion {
            get {
                return ResourceManager.GetString("RotateQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Does the engine run normally?.
        /// </summary>
        internal static string RunQuestion {
            get {
                return ResourceManager.GetString("RunQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is the engine sluggish?.
        /// </summary>
        internal static string SluggishQuestion {
            get {
                return ResourceManager.GetString("SluggishQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Does the engine start?.
        /// </summary>
        internal static string StartQuestion {
            get {
                return ResourceManager.GetString("StartQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to the Engine Diagnosis Expert System..
        /// </summary>
        internal static string WelcomeMessage {
            get {
                return ResourceManager.GetString("WelcomeMessage", resourceCulture);
            }
        }
    }
}
